### ISSUE TITLE
NEW PROJECT: BMI CALCULATOR

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [SamarthTech/Web-Development-Projects#31]
@SamarthTech , I want to add a new project a BMI calculator using Html, CSS and JS.
Please assign  me this feature under Hacktoberfest 2023 contributor

**Comment by codingniket** [comment]
No need to open a issue make just make pull request

**Comment by MOHDNEHALKHAN** [comment]
Ok
Thanks for the Reply😊
