### ISSUE TITLE
game

### ISSUE THREAD

**Issue by NaMiKA0305** [SamarthTech/Web-Development-Projects#51]
can you assign me this snake game which is created by html css and javascript.it is old snake game which we found in small keypad nokia cellphone.
![Screenshot (109)](https://github.com/SamarthTech/Web-Development-Projects/assets/98265007/06056f0c-f0e7-4064-b87f-bedefe0592a2)

**Comment by codingniket** [comment]
Just give a pull request no need to raise a issue!

**Comment by NaMiKA0305** [comment]
sir, i sent you snakegame pr please merge it.

**Comment by NaMiKA0305** [comment]
Heyy sir , plzz merge my pr. Do me this favour

**Comment by NaMiKA0305** [comment]
Hello samarthTech/Web-Development-Projects,
Can you pls merge my  pr. snakegame

**Comment by codingniket** [comment]
Check

**Comment by NaMiKA0305** [comment]
Got it! Thnks.
