### ISSUE TITLE
Recipe Finder

### ISSUE THREAD

**Issue by prathimacode-hub** [SamarthTech/Web-Development-Projects#53]
This Recipe Finder project would demonstrate in searching out the recipes using keyword by themealdb API.

I  would like to work on this issue under hacktoberfest. Can you assign this issue to me? @SamarthTech

**Comment by codingniket** [comment]
Go Ahead

**Comment by prathimacode-hub** [comment]
I had created my PR here : https://github.com/SamarthTech/Web-Development-Projects/pull/54. Kindly review and merge it with "Hacktoberfest-Accepted" label. Thank You. @codingniket
