### ISSUE TITLE
project add: random quote app generator 

### ISSUE THREAD

**Issue by Gurnav224** [SamarthTech/Web-Development-Projects#55]
![Screenshot from 2023-10-11 11-04-35](https://github.com/SamarthTech/Web-Development-Projects/assets/72142482/2ff62881-2b69-46e2-8345-e73c1dc7d7a9)

**Comment by Anuj-Gill** [comment]
Please assign this to me, i have already created this random quote generator. You can check it out [here](https://anuj-gill.github.io/quote_Generator/#)

**Comment by codingniket** [comment]
Go Ahead

**Comment by Anuj-Gill** [comment]
Thanks for assigning this issue to me @codingniket . I recently made a PR #52 (Random quote generator) which got merged and that project resolves this issue. Please mark this issue as resolved with respect to that pull request. Do let me know if anything is to be done from my side.
