### ISSUE TITLE
Honey commercial store frontend UI 

### ISSUE THREAD

**Issue by Bhushan001S** [SamarthTech/Web-Development-Projects#67]
Website of honey commercial store for selling various honey based products using HTML,CSS and Javascript . 
![image](https://github.com/SamarthTech/Web-Development-Projects/assets/102133759/95eb6057-5d8b-4334-b7dd-e461291cee2b)

**Comment by 08Uzair** [comment]
Please assign this to me

**Comment by codingniket** [comment]
No need to create a issue just make a pull request

**Comment by 08Uzair** [comment]
Please assign this to me

**Comment by 08Uzair** [comment]
Should i make the same figma as above or shall i make some changes in the above  figma

**Comment by codingniket** [comment]
No need to create a figma file,
Step 1 : Write the code 
Step 2 : Make a pull request
